@set allusersprofile=c:\programdata
@set appdata=c:\users\hp\appdata\roaming
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=desktop-ftf9mog
@set comspec=c:\windows\system32\cmd.exe
@set depot_tools_win_toolchain=0
@set devenvdir=d:\microsoft visual studio 14.0\common7\ide\
@set docker_toolbox_install_path=d:\docker toolbox
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set homedrive=c:
@set homepath=\users\hp
@set include=d:\microsoft visual studio 14.0\vc\include;d:\microsoft visual studio 14.0\vc\atlmfc\include;c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\8.1\include\\shared;c:\program files (x86)\windows kits\8.1\include\\um;c:\program files (x86)\windows kits\8.1\include\\winrt
@set lib=d:\microsoft visual studio 14.0\vc\lib;d:\microsoft visual studio 14.0\vc\atlmfc\lib;c:\program files (x86)\windows kits\10\lib\10.0.10240.0\ucrt\x86;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x86;c:\program files (x86)\windows kits\8.1\lib\winv6.3\um\x86
@set libpath=c:\windows\microsoft.net\framework\v4.0.30319;d:\microsoft visual studio 14.0\vc\lib;d:\microsoft visual studio 14.0\vc\atlmfc\lib;c:\program files (x86)\windows kits\8.1\references\commonconfiguration\neutral;\microsoft.vclibs\14.0\references\commonconfiguration\neutral
@set localappdata=c:\users\hp\appdata\local
@set logonserver=\\desktop-ftf9mog
@set moz_plugin_path=d:\tracker software\pdf viewer\win32\
@set msbuildloadmicrosofttargetsreadonly=true
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set number_of_processors=4
@set os=windows_nt
@set path=d:\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\msbuild\14.0\bin;d:\microsoft visual studio 14.0\common7\ide\;d:\microsoft visual studio 14.0\vc\bin;d:\microsoft visual studio 14.0\common7\tools;c:\windows\microsoft.net\framework\v4.0.30319;d:\microsoft visual studio 14.0\vc\vcpackages;c:\program files (x86)\html help workshop;d:\microsoft visual studio 14.0\team tools\performance tools;c:\program files (x86)\windows kits\8.1\bin\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\;d:\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\teamfoundation\team explorer\nativebinaries\x86;c:\programdata\oracle\java\javapath;c:\program files\broadcom\broadcom 802.11 network adapter;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files (x86)\skype\phone\;c:\users\hp\.dnx\bin;c:\program files\microsoft dnx\dnvm\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files (x86)\nvidia corporation\physx\common;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\windows kits\8.1\windows performance toolkit\;c:\program files\microsoft sql server\120\tools\binn\;c:\program files\microsoft\web platform installer\;c:\program files\dotnet\;c:\program files\git\cmd;c:\wxwidgets-3.1.0;c:\src\depot_tools;c:\program files (x86)\visual leak detector\bin\win32;c:\program files (x86)\visual leak detector\bin\win64;d:\miktex 2.9\miktex\bin\x64\;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\python34\;c:\python34\scripts\;d:\docker toolbox;c:\users\hp\appdata\local\microsoft\windowsapps;d:\microsoft visual studio 14.0\vc\bin;c:\users\hp\downloads\ffmpeg-20170123-e371f03-win64-static\bin
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\hp\appdata\local\microsoft\visualstudio\14.0\devenv.exe.config
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 78 stepping 3, genuineintel
@set processor_level=6
@set processor_revision=4e03
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules;c:\program files\windowspowershell\modules\;c:\program files (x86)\microsoft sdks\azure\powershell\resourcemanager\azureresourcemanager\;c:\program files (x86)\microsoft sdks\azure\powershell\servicemanagement\;c:\program files (x86)\microsoft sdks\azure\powershell\storage\
@set public=c:\users\public
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\hp\appdata\local\temp
@set tmp=c:\users\hp\appdata\local\temp
@set ucrtversion=10.0.10240.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=desktop-ftf9mog
@set userdomain_roamingprofile=desktop-ftf9mog
@set username=hp
@set userprofile=c:\users\hp
@set vbox_msi_install_path=d:\virtual box\
@set vcinstalldir=d:\microsoft visual studio 14.0\vc\
@set visualstudiodir=c:\users\hp\documents\visual studio 2015
@set visualstudioedition=microsoft visual studio community 2015
@set visualstudioversion=14.0
@set vs140comntools=d:\microsoft visual studio 14.0\common7\tools\
@set vsinstalldir=d:\microsoft visual studio 14.0\
@set vslang=1033
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\8.1\references\commonconfiguration\neutral
@set windowssdkdir=c:\program files (x86)\windows kits\8.1\
@set windowssdklibversion=winv6.3\
@set windowssdkversion=\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\
@set wxwin=c:\wxwidgets-3.1.0
@set _ptvs_pid=20076

@call cl.exe